### PR TITLE
adds a cookbook icon

### PR DESCRIPTION
**Pull request by timothypratley**

### CODE REVIEW

**Comment by timothypratley** [comment]
@kiramclean What do you think about this shape?

**Comment by kirahowe** [comment]
This looks great! Happy to use it going forward, also happy to compromise to match the rest of the group others prefer a different shape/type of outline. I think the very mild preference I have for any given outline would be outweighed by the benefit of all matching each other.

**Comment by timothypratley** [comment]
@daslu can you please merge this? I don't have write permission

**Comment by kirahowe** [comment]
Just doing some github housekeeping this morning.. looks like I can merge this. Thanks for all the amazing icons @timothypratley!

**Comment by timothypratley** [comment]
great, thank you! 😄

**Pull request merged**
